### ISSUE TITLE
Library Architecture Proposal: Separating KMP and Compose for Enhanced Flexibility

### ISSUE THREAD

**Issue by adamglin0** [kalinjul/EasyQRScan#13]
I believe this library should be divided into two parts: **kmp** and **compose**.

The compose part is only responsible for capturing images and transmitting the images to the **kmp part**.

The **kmp part** is responsible for processing and recognizing the code.

Following this architecture can make the library widely used, as there will be users who only use KMP.

**Comment by kalinjul** [comment]
I can see the reasoning behind your idea, but in both iOS and Android the image processing is tightly coupled to the UI, which kind of makes sense, because you want a live-preview anyway.

There are no single images passed to some function that we could provide as kmp-only library.
If you do Barcode Scanning in a non-compose KMP-App, there's likely no multiplatform code involved at all until you get the scan result.
