### ISSUE TITLE
Code128

### ISSUE THREAD

**Issue by andiosdev** [kalinjul/EasyQRScan#7]
Hi, this does not scan a code128 type. Tried with QR and it's working,

**Comment by kalinjul** [comment]
Can you provide more detail? On which platform does this not scan code128? Did you specify code128 as type?

**Comment by DevinDuricka** [comment]
Code 128 seems to work on Android, but not iOS

**Comment by hrn1999** [comment]
Hi, are there any updates regarding this issue? Also, all EAN formats are not being read on iOS, although they work fine on Android.

**Comment by kalinjul** [comment]
Thanks for the PR, fixed in 0.1.6 which should be available any minute.

**Comment by SofienTouati-ProxymIT** [comment]
hello, still facing this issue in version 0.2.0, i've tries the sample code by changing the types, it only works with QRCode.

the issue is in `List<CodeType>.toFormat()` extension function, you can see the eror in the screenshot below.

![Image](https://github.com/user-attachments/assets/bee778ed-444c-41e2-8e82-dcad0b251218)
